package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"strconv"

	"github.com/ritarock/manga/graph/model"
)

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	books := []*model.Book{}
	searched, _ := r.EntClient.Book.Query().Limit(100).All(ctx)
	for _, book := range searched {
		books = append(books, &model.Book{
			ID:          strconv.Itoa(book.ID),
			Isbn:        book.Title,
			Title:       book.Title,
			Publisher:   book.Publisher,
			Pubdate:     book.Publisher,
			Cover:       book.Cover,
			Author:      book.Author,
			SubjectCode: book.SubjectCode,
		})
	}
	return books, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
