// Code generated by ent, DO NOT EDIT.

package book

const (
	// Label holds the string label denoting the book type in the database.
	Label = "book"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIsbn holds the string denoting the isbn field in the database.
	FieldIsbn = "isbn"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldPublisher holds the string denoting the publisher field in the database.
	FieldPublisher = "publisher"
	// FieldPubdate holds the string denoting the pubdate field in the database.
	FieldPubdate = "pubdate"
	// FieldCover holds the string denoting the cover field in the database.
	FieldCover = "cover"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldSubjectCode holds the string denoting the subject_code field in the database.
	FieldSubjectCode = "subject_code"
	// Table holds the table name of the book in the database.
	Table = "books"
)

// Columns holds all SQL columns for book fields.
var Columns = []string{
	FieldID,
	FieldIsbn,
	FieldTitle,
	FieldPublisher,
	FieldPubdate,
	FieldCover,
	FieldAuthor,
	FieldSubjectCode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
